#include <furi.h>
#include <furi_hal.h>

#include <gui/gui.h>
#include <input/input.h>

/* Magic happens here -- this file is generated by fbt.
 * Just set fap_icon_assets in application.fam and #include {APPID}_icons.h */
#include "test_icons.h"

typedef struct {
    uint8_t x, y;
} ImagePosition;

static ImagePosition image_position = {.x = 0, .y = 0};
const Icon* icons[] = {&I_Meme, &I_Meme2, &I_Meme3, &I_Meme4, &I_Meme5, &I_Meme6};
uint iconsCounter = 0;
uint iconsSize = 5;

// Screen is 128x64 px
static void app_draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);

    canvas_clear(canvas);
    canvas_draw_icon(canvas, image_position.x % 128, image_position.y % 64, icons[iconsCounter]);
    canvas_draw_icon(canvas, 104, 51, &I_Arrows);
}

static void app_input_callback(InputEvent* input_event, void* ctx) {
    furi_assert(ctx);

    FuriMessageQueue* event_queue = ctx;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

int32_t test_app(void* p) {
    UNUSED(p);
    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    // Configure view port
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, app_draw_callback, view_port);
    view_port_input_callback_set(view_port, app_input_callback, event_queue);

    // Register view port in GUI
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    InputEvent event;

    bool running = true;
    while(running) {
        if(furi_message_queue_get(event_queue, &event, 100) == FuriStatusOk) {
            if(event.type == InputTypePress) {
                if(event.key == InputKeyRight && iconsCounter < iconsSize) iconsCounter++;
                if(event.key == InputKeyLeft && iconsCounter > 0) iconsCounter--;
                if(event.key == InputKeyBack) running = false;
            }
        }
    }
    view_port_update(view_port);

    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_message_queue_free(event_queue);

    furi_record_close(RECORD_GUI);

    return 0;
}

// switch(event.key) {
//     case InputKeyLeft:
//         if(iconsCounter > 0)
//             iconsCounter--;
//         else if(iconsCounter == 0)
//             iconsCounter = iconsSize;
//         else
//             break;
//         break;
//     case InputKeyRight:
//         if(iconsCounter < iconsSize)
//             iconsCounter++;
//         else if(iconsCounter == iconsSize)
//             iconsCounter = 0;
//         else
//             break;
//         break;
//     default:
//         running = false;
//         break;
// }